<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure to delete this item?' => 'Ви впевнені, що хочете видалити цей елемент?',
    'Category' => 'Категорія',
    'Copy' => 'Копіювати',
    'Create' => 'Створювати',
    'Delete' => 'Видалити',
    'Edit' => 'Редагувати',
    'First' => 'Перше',
    'Full list' => 'Повний список',
    'Image not uploaded, please try again later.' => 'Зображення не завантажено, будь ласка, повторіть спробу пізніше.',
    'Image was not deleted, please try again later' => 'Зображення не було видалено, будь ласка, повторіть спробу пізніше',
    'Last' => 'Останній',
    'List' => 'Список',
    'New' => 'Новий',
    'On main' => 'На головному',
    'Product' => 'Продукт',
    'Reset' => 'Скидання',
    'Save' => 'Зберегти',
    'Search' => 'Пошук',
    'Select' => 'Вибрати',
    'View' => 'Дивитися',
    'Without group' => 'Без групи',
    'Выберите пункт из меню слева.' => 'Виберіть пункт з меню зліва.',
    'Youtube Link' => 'iframe Youtube',
];
