<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Address' => 'Адрес',
    'Apartment Complex' => 'Житловий Комплекс',
    'Apartment Complexes' => 'Житлові комплекси',
    'Cart' => 'Кошик',
    'Cart ID' => '',
    'Cart Product' => 'Кошик Товарів',
    'Cart Products' => 'Кошик Товарів',
    'Carts' => 'Кошик',
    'Categories' => 'Категорії',
    'Category' => 'Категорія',
    'Category ID' => 'Категорія',
    'Complex ID' => 'Назва ЖК',
    'Complex Product' => 'Товар ЖК',
    'Complex Products' => 'Товари ЖК',
    'Cost' => 'Вартість',
    'Count' => 'Кількість',
    'Created At' => 'Дата замовлення',
    'Customer' => 'Покупець',
    'Delivery' => 'Доставка',
    'Description' => 'Опис',
    'Email' => 'Електронна пошта',
    'Full Name' => "Повне ім'я",
    'General Cost' => 'Вартість',
    'General Count' => 'Кількість',
    'Home Slider' => 'Головний слайдер',
    'Home Sliders' => 'Головний слайдер',
    'ID' => '',
    'Image' => 'Зображення',
    'Language' => 'Мова',
    'Message' => 'Повідомлення',
    'Messages' => 'Повідомлення',
    'Name' => 'Назва',
    'Phone Number' => 'Номер телефону',
    'Popular Product' => 'Популярні продукт',
    'Popular Products' => 'Популярні продукти',
    'Product' => 'Товар',
    'Product Code' => 'Код продукту',
    'Product ID' => 'Назва товару',
    'Product Link' => 'Посилання продукту',
    'Products' => 'Товари',
    'Source ID' => '',
    'Source Message' => 'Вихідне повідомлення',
    'Source Messages' => 'Вихідні повідомлення',
    'Status Order' => 'Статус замовлення',
    'Translation' => 'Переклад',
    'Updated At' => 'Змінено в',
    'Youtube Link' => 'iframe Youtube',
    'Youtube Slider' => 'Слайдер Youtube',
    'Youtube Sliders' => 'Слайдери Youtube',
    'Адрес' => 'Адрес',
    'Адрес ЖК' => 'Адрес ЖК',
    'Дата редактирования записи' => '',
    'Дата создания записи' => 'Дата редагування запису',
    'Заголовок слайдера' => 'Заголовок слайдера',
    'Изображение' => 'Зображення',
    'Изображение товара' => 'Зображення товару',
    'Код товара' => 'Код товару',
    'Количество товара' => 'Кількість товару',
    'Название ЖК' => 'Назва ЖК',
    'Название видео' => 'Назва відео',
    'Название категории' => 'Назва категорії',
    'Название продукта' => 'Назва продукту',
    'Название товара' => 'Назва товару',
    'Номер телефона' => 'Номер телефону',
    'Общая стоимость товара' => 'Загальна вартість товару',
    'Общее количество товара' => 'Загальна кількість товару',
    'Описание ЖК' => 'Опис ЖК',
    'Описание слайдера' => 'Опис слайдера',
    'Описание товара' => 'Опис товару',
    'Способ доставки' => 'Спосіб доставки',
    'Ссылка на видео ютуб' => 'ifram відео youtube',
    'Ссылка на продукт' => 'Посилання на продукт',
    'Статус заказа' => 'Статус замовлення',
    'Стоимость товара' => 'Вартість товару',
    'ФИО' => "Повне ім'я",
    'Электронная почта' => 'Електронна пошта',
    'Complex Name' => 'Назва ЖК',
    'Product Name' => 'Назва товару',
    'Category Name' => 'Назва категорії',
];
